### PR TITLE
Update LICENSE.md

### PR DESCRIPTION
**Pull request by superkhau**
Copied from Loopback (repo name in license modified to match this repo name).

cc @chandadharap @rmg

### CODE REVIEW

**Comment by superkhau** [comment]
cc @rmg

**Comment by rmg** [comment]
This is missing a bunch of the changes necessary for a relicensing. @superkhau rather than list them all, I'm just going to push up the changes to your branch. They're all machine generated.

**Comment by superkhau** [comment]
@rmg Your changes LGTM.

**Comment by rmg** [comment]
And the changes are entirely mine so my approval wouldn't really mean anything. @qpresley @chandadharap are you able to rubber stamp this?

**Pull request merged**
