### PR TITLE
Update oauth-authorization-code.json

### PR DESCRIPTION
**Pull request by thovden**
MySQL using utf-8 cannot use keys larger than 768 bytes. Reducing the size of this key slightly. 

http://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by loay** [comment]
@slnode test please

**Comment by loay** [comment]
Hi @thovden 
Please sign the agreement. Also, reduce the size of the commit message. The maximum is 70 characters. Thanks.

**Comment by thovden** [comment]
Sign what agreement?

**Comment by loay** [comment]
this one: https://cla.strongloop.com/agreements/strongloop/loopback-component-oauth2

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
