### PR TITLE
Further integration between OAuth2 and LoopBack

### PR DESCRIPTION
**Pull request by JonnyBGod**
### Description

WIP

Better integrate oauth2 component with loopback.
1. Unify the access token model between oAuth 2.0 and User.login
2. Integrate scope with ACL

#### Related issues

https://github.com/strongloop/loopback/issues/817

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

Missing:
 - [ ] Tests for OAuthUser

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by raymondfeng** [comment]
@JonnyBGod Thank you for the patch. I'll find some time to review it.

**Comment by JonnyBGod** [comment]
@raymondfeng This is not finished as I still need to implement tests for it. But before that I would appreciate an overall review on my approach.

**Comment by drmikecrowe** [comment]
@JonnyBGod How exactly does this integrate within the Loopback ACL system?

I have a fork I'm working on of loopback-swagger that adds the securityDefinitions and security sections to swagger.json.  Now, I'm searching for how to add the OAuth2 scopes to a method (built-in or remote).  The global scope works fine.

Example:  In components-config.json:
```json
	"securityDefinitions": {
		"OauthSecurity": {
			"type": "oauth2",
			"flow": "accessCode",
			"name": "access_token",
			"authorizationUrl": "http://localhost:3006/oauth/authorization",
			"tokenUrl": "http://localhost:3006/oauth/token",
			"scopes": {
				"read": "Read Only Permission",
				"write": "Read/Write Permission"
			}
		}
	},
	"security": [
		{
			"OauthSecurity": [
				"read"
			]
		}
	]
```

However, in a given method, we need (as an example) the method to specify the scope restriction such the following:
```json
  "/Devices/{id}/removeDevice": {
    "post": {
      "tags": [
        "Device"
      ],
      "operationId": "Device.removeDevice",
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Device ID",
          "required": true,
          "type": "string"
        }
      ],
      "responses": {
        "200": {
          "description": "Request was successful",
          "schema": {
            "description": "Returns the deleted Device if successful",
            "$ref": "#/definitions/Device"
          }
        }
      },
      "deprecated": false,
      "security": [
        {
          "OauthSecurity": [
            "write"
          ]
        }
      ]
    }
  }
```

**Comment by JonnyBGod** [comment]
I just mean that resolving ACLs is working fine with this patch.
Have not actually tested scopes. Might need more work for that to work.

**Comment by drmikecrowe** [comment]
@raymondfeng What was the long-term plan for how to integrate OAuth2 scopes into ACL's?

Would integrating them into ACL's using a different role be acceptable?
```JSON
  "acls": [
    {
      "accessType": "READ",
      "principalType": "OAUTH2",
      "principalId": "read",
      "permission": "ALLOW"
    }
  ]
```

**Comment by drmikecrowe** [comment]
NOTE:  I'm working on a loopback-swagger fork which impacts this:  It's a work-in-progress that supports the *configuration* of OAuth2 in the swagger.json. Still needs automated tests, but the results work perfectly in http://editor.swagger.io/#!/

https://github.com/drmikecrowe/loopback-swagger

**Comment by raymondfeng** [comment]
@drmikecrowe This PR will get us close to oAuth2 alignment - https://github.com/strongloop/loopback/pull/3313.

**Pull request closed without merging**
