### PR TITLE
Failed login uri

### PR DESCRIPTION
**Pull request by wascou**
see https://github.com/strongloop/loopback-component-oauth2/issues/21

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by loay** [comment]
test please

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by Amir-61** [comment]
Hey @wascou 

Could you please clarify what you are trying to solve in this PR; to verify the changes could you also please add tests?

Last but not least the patch is behind master branch; could you rebase it on top of master branch? Once they are done please ping me for review...

Thanks!

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
