### PR TITLE
Further integration between OAuth2 and LoopBack

### PR DESCRIPTION
**Pull request by JonnyBGod**
### Description

WIP

Better integrate oauth2 component with loopback.
1. Unify the access token model between oAuth 2.0 and User.login
2. Integrate scope with ACL

#### Related issues

https://github.com/strongloop/loopback/issues/817

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

Missing:
 - [ ] Tests for OAuthUser

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by JonnyBGod** [comment]
Let me know what do you think of the approach.

I am not entirely sure if I have covered all related aspects.

**Pull request closed without merging**
